name: Python build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [ ubuntu-latest, macos-latest, windows-latest ]
          python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up non-Windows dependencies
      if: matrix.os != 'windows-latest'
      shell: bash -l {0}
      run: |
        pip install -r requirements.txt
        pip install -r tests/requirements.txt
    - name: Set up Windows dependencies
      if: matrix.os == 'windows-latest'
      shell: cmd /C CALL {0}
      run: |
        pip install -r requirements.txt
        pip install -r tests\requirements.txt
    - name: Run tests on Windows
      if: matrix.os == 'windows-latest'
      shell: cmd /C CALL {0}
      run: ./cicd/run_tests.bat
    - name: Run tests on non-Windows
      if: matrix.os != 'windows-latest'
      shell: bash -l {0}
      run: |
        chmod 775 cicd/run_tests.sh
        ./cicd/run_tests.sh
    - name: Coveralls
      if: matrix.os == 'ubuntu-latest'
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        debug: true
